name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: [self-hosted, Linux]
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2
        - name: Install Rust
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: 1.75.0
            targets: wasm32-unknown-unknown
        - name: Compile
          run: cargo build --lib --target wasm32-unknown-unknown --release
        - name: Test
          run: cargo test -- --nocapture