name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Rust
          uses: ATiltedTree/setup-rust@v1
          with:
            rust-version: 1.75.0

        - name: Install wasm32-unknown-unknown
          run: rustup target add wasm32-unknown-unknown

        - name: Compile
          run: cargo build --lib --target wasm32-unknown-unknown --release

        - name: Test
          run: |
            cd tests
            cargo test -- --nocapture